feat(IntentSource): vault based intents
eco/eco-routes pull request #128
Opened 2024-12-16 21:17 UTC by re1ro

* [x] `IntentSource`: storage-less intents

2024-12-17 00:09 UTC, carlosfebres reviewed
It's looking great! I left a couple of questions

2024-12-18 22:13 UTC, nknavkal commented
can this PR be against main rather than AUDIT? just dont want to mix those changes up order-wise

2025-01-17 19:57 UTC, StoyanD requested changes
added some comments around syntax and gas.

im wondering if we can fit for of the conditions of the withdraw function in the intentsource to the vault because it sort of splits the logic into two places

2025-01-17 19:57 UTC, StoyanD commented on contracts/IntentVault.sol
> +            state.status == uint8(IIntentSource.ClaimStatus.Claimed)
if the status is claimed, should this return instead of transferring the tokens?

2025-01-17 19:57 UTC, StoyanD commented on contracts/IntentSource.sol
> +        new IntentVault{salt: routeHash}(intentHash, reward);
is there a way to fold all the code below the first if statement into the vault code?

2025-01-20 22:24 UTC, nknavkal commented on contracts/IntentSource.sol
> +            if (!_validateIntent(intent, vault)) {
why are we validating the intent if it isnt being funded? are you not allowed to create an intent before funding it? test cases do not cover situations where fundRewards is false

2025-01-21 17:51 UTC, StoyanD commented on contracts/interfaces/IIntentSource.sol
> +        uint256 destination,
how come we are updating the indexing fields?

2025-01-24 17:16 UTC, re1ro commented on contracts/Inbox.sol
> +        if (!isSolvingPublic && !solverWhitelist[msg.sender]) {
I moved the modifier inline as it was used only on 1 place. No reusability there.
Also modifiers are usually used for the external functions

2025-01-24 17:39 UTC, re1ro commented on contracts/IntentSource.sol
> +                uint256 amount = reward.tokens[i].amount;
Maybe a little bit, but could be optimized by compiler. I did for readability initially, but just inlined it for simplicity

2025-01-24 17:40 UTC, re1ro commented on contracts/IntentSource.sol
> +        } else if (block.chainid == intent.route.source) {
We now can publish intents on a different chain. It's a new feature
 But this check is getting removed.

2025-01-24 17:46 UTC, re1ro commented on contracts/IntentSource.sol
> +    function _validateIntent(
renamed into `isIntentFunded` 👍

2025-01-24 17:51 UTC, re1ro commented on contracts/IntentSource.sol
> +            revert UnauthorizedWithdrawal(intentHash);
I agree, I just kept it as it was. Fixed now

2025-01-24 17:53 UTC, re1ro commented on contracts/IntentSource.sol
> +        new IntentVault{salt: routeHash}(intentHash, reward);
Yup good idea, now refund will be done only through refund function.

2025-01-24 17:53 UTC, re1ro commented on contracts/IntentVault.sol
> +            if (token == refundToken) {
Gas optimizations are not usually tuned for the revert scenarios

2025-01-24 17:55 UTC, re1ro commented on contracts/IntentVault.sol
> +            if (claimant == reward.creator) {
People do mistakes haha. Think about customer satisfaction, even if they do something wrong. 
Like sending USDT instead of USDC. Or typing an extra 0 in the token amount and sending it

2025-01-24 18:06 UTC, re1ro commented on contracts/IntentVault.sol
> +    receive() external payable {}
Good point, it's only needed if that contract if unwrapping ETH or doing something else to receive ETH

2025-01-24 18:07 UTC, re1ro commented on contracts/IntentSource.sol
> +    function refundIntent(
Good point, I think it's good to have for transparency

2025-01-24 18:25 UTC, re1ro commented on contracts/IntentSource.sol
> +            if (!_validateIntent(intent, vault)) {
Removed that check 👍

2025-01-24 18:37 UTC, re1ro commented on contracts/interfaces/IIntentSource.sol
> +        uint256 destination,
yeah we are using off-chain indexer anyway. I don't see how indexing by `destination` would be useful for anyone.

Instead I've created an index for `creator`, which could be handy to query by some front end

2025-01-24 19:08 UTC, StoyanD commented on contracts/interfaces/IIntentSource.sol
> +        uint256 destination,
ok, just discuss before hand because i didnt expect the index to change. added some work for me on the backend

2025-01-24 19:29 UTC, StoyanD approved these changes

2025-01-24 19:29 UTC, re1ro commented on contracts/IntentSource.sol
> +    ) internal view returns (address) {
I think it's a view because of accessing `address(this)`

2025-01-24 19:34 UTC, re1ro commented on contracts/IntentSource.sol
> +                revert UnauthorizedWithdrawal(intentHash);
We are marking it as Refunded now

2025-01-24 20:23 UTC, nknavkal commented on contracts/IntentVault.sol
> -    receive() external payable {}
ok wait so before the contract itself is created, the address is an EOA so can receive by default? there is no need to receive when this is a contract, since it will be created and destroyed in once tx?

2025-01-24 20:26 UTC, nknavkal approved these changes
lgtm

2025-01-24 22:28 UTC, merged